import { Inter } from 'next/font/google';
import '../styles/layout/layout.scss';
import '../styles/demo/Demos.scss';
import '../styles/globals.css';
import { LayoutProvider } from '@/layout/context/layoutcontext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          id="theme-css"
          href={`/themes/lara-light-blue/theme.css`}
          rel="stylesheet"
        ></link>
      </head>
      <body className={inter.className}>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
